### ISSUE TITLE
main执行报错

### ISSUE THREAD

**Issue by fxyouruo** [wenet-e2e/WeTextProcessing#117]
大佬们好，在不使用pip安装的前提下，执行 python itn/main.py --text "上午8点半"，出现下面的错误是什么原因呢？

Traceback (most recent call last):
  File "/data/WeTextProcessing-master/itn/main.py", line 59, in <module>
    main()
  File "/data/WeTextProcessing-master/itn/main.py", line 43, in main
    normalizer = InverseNormalizer(
  File "/data/WeTextProcessing-master/itn/chinese/inverse_normalizer.py", line 41, in __init__
    self.build_fst('zh_itn', cache_dir, overwrite_cache)
  File "/data/WeTextProcessing-master/itn/processor.py", line 74, in build_fst
    self.build_tagger()
  File "/data/WeTextProcessing-master/itn/chinese/inverse_normalizer.py", line 44, in build_tagger
    tagger = (add_weight(Date().tagger, 1.02)
  File "/data/WeTextProcessing-master/itn/chinese/rules/date.py", line 25, in __init__
    self.build_tagger()
  File "/data/WeTextProcessing-master/itn/chinese/rules/date.py", line 29, in build_tagger
    digit = string_file('itn/chinese/data/number/digit.tsv')  # 1 ~ 9
  File "extensions/_pynini.pyx", line 1033, in _pynini.string_file
  File "extensions/_pynini.pyx", line 1109, in _pynini.string_file
_pywrapfst.FstIOError: Read failed

期待大佬们指点一下！
祝好！

**Comment by xingchensong** [comment]
下班了，明天看👀

**Comment by xingchensong** [comment]
![image](https://github.com/wenet-e2e/WeTextProcessing/assets/13466943/29033e4d-0d46-45d4-81a6-53c80593a1af)

你需要换一种启动方式，请详细阅读 readme
