### ISSUE TITLE
测试报错

### ISSUE THREAD

**Issue by HankLiu10** [wenet-e2e/WeTextProcessing#120]
你好，我想运行WeTextProcessing-master/itn/chinese/test下的normalizer_test.py进行测试，报错如下：
Traceback (most recent call last):
  File "normalizer_test.py", line 23, in <module>
    class TestNormalizer:
  File "normalizer_test.py", line 25, in TestNormalizer
    normalizer = InverseNormalizer(
  File "/storage1/liuhangchen/anaconda3/envs/wenetITN/lib/python3.8/site-packages/itn/chinese/inverse_normalizer.py", line 41, in __init__
    self.build_fst('zh_itn', cache_dir, overwrite_cache)
  File "/storage1/liuhangchen/anaconda3/envs/wenetITN/lib/python3.8/site-packages/tn/processor.py", line 74, in build_fst
    self.build_tagger()
  File "/storage1/liuhangchen/anaconda3/envs/wenetITN/lib/python3.8/site-packages/itn/chinese/inverse_normalizer.py", line 44, in build_tagger
    tagger = (add_weight(Date().tagger, 1.02)
  File "/storage1/liuhangchen/anaconda3/envs/wenetITN/lib/python3.8/site-packages/itn/chinese/rules/date.py", line 25, in __init__
    self.build_tagger()
  File "/storage1/liuhangchen/anaconda3/envs/wenetITN/lib/python3.8/site-packages/itn/chinese/rules/date.py", line 29, in build_tagger
    digit = string_file('itn/chinese/data/number/digit.tsv')  # 1 ~ 9
  File "extensions/_pynini.pyx", line 1033, in _pynini.string_file
  File "extensions/_pynini.pyx", line 1109, in _pynini.string_file
_pywrapfst.FstIOError: Read failed

请问如何解决，谢谢！

**Comment by xingchensong** [comment]
duplicate issue，#119
