### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by HankLiu10** [wenet-e2e/WeTextProcessing#129]
您好，上周解决后，这周再次出现相同报错，已安装wetextprocessing包：
(wenetITN) liuhangchen@G08:~/WeNetITN$ weitn --text "二点五平方电线"
Traceback (most recent call last):
  File "/storage1/liuhangchen/anaconda3/envs/wenetITN/bin/weitn", line 8, in <module>
    sys.exit(main())
  File "/storage1/liuhangchen/anaconda3/envs/wenetITN/lib/python3.8/site-packages/itn/main.py", line 43, in main
    normalizer = InverseNormalizer(
  File "/storage1/liuhangchen/anaconda3/envs/wenetITN/lib/python3.8/site-packages/itn/chinese/inverse_normalizer.py", line 42, in __init__
    self.build_fst('zh_itn', cache_dir, overwrite_cache)
  File "/storage1/liuhangchen/anaconda3/envs/wenetITN/lib/python3.8/site-packages/tn/processor.py", line 74, in build_fst
    self.build_tagger()
  File "/storage1/liuhangchen/anaconda3/envs/wenetITN/lib/python3.8/site-packages/itn/chinese/inverse_normalizer.py", line 45, in build_tagger
    tagger = (add_weight(Date().tagger, 1.02)
  File "/storage1/liuhangchen/anaconda3/envs/wenetITN/lib/python3.8/site-packages/itn/chinese/rules/date.py", line 25, in __init__
    self.build_tagger()
  File "/storage1/liuhangchen/anaconda3/envs/wenetITN/lib/python3.8/site-packages/itn/chinese/rules/date.py", line 29, in build_tagger
    digit = string_file('itn/chinese/data/number/digit.tsv')  # 1 ~ 9
  File "extensions/_pynini.pyx", line 1033, in _pynini.string_file
  File "extensions/_pynini.pyx", line 1109, in _pynini.string_file
_pywrapfst.FstIOError: Read failed

**Comment by HankLiu10** [comment]
> 您好，上周解决后，这周再次出现相同报错，已安装wetextprocessing包： (wenetITN) liuhangchen@G08:~/WeNetITN$ weitn --text "二点五平方电线" Traceback (most recent call last): File "/storage1/liuhangchen/anaconda3/envs/wenetITN/bin/weitn", line 8, in sys.exit(main()) File "/storage1/liuhangchen/anaconda3/envs/wenetITN/lib/python3.8/site-packages/itn/main.py", line 43, in main normalizer = InverseNormalizer( File "/storage1/liuhangchen/anaconda3/envs/wenetITN/lib/python3.8/site-packages/itn/chinese/inverse_normalizer.py", line 42, in **init** self.build_fst('zh_itn', cache_dir, overwrite_cache) File "/storage1/liuhangchen/anaconda3/envs/wenetITN/lib/python3.8/site-packages/tn/processor.py", line 74, in build_fst self.build_tagger() File "/storage1/liuhangchen/anaconda3/envs/wenetITN/lib/python3.8/site-packages/itn/chinese/inverse_normalizer.py", line 45, in build_tagger tagger = (add_weight(Date().tagger, 1.02) File "/storage1/liuhangchen/anaconda3/envs/wenetITN/lib/python3.8/site-packages/itn/chinese/rules/date.py", line 25, in **init** self.build_tagger() File "/storage1/liuhangchen/anaconda3/envs/wenetITN/lib/python3.8/site-packages/itn/chinese/rules/date.py", line 29, in build_tagger digit = string_file('itn/chinese/data/number/digit.tsv') # 1 ~ 9 File "extensions/_pynini.pyx", line 1033, in _pynini.string_file File "extensions/_pynini.pyx", line 1109, in _pynini.string_file _pywrapfst.FstIOError: Read failed

补充一下，pynini版本为2.1.5

**Comment by xingchensong** [comment]
需要在git clone的目录下运行weitn

**Comment by xingchensong** [comment]
找到问题了等会改一下

**Comment by xingchensong** [comment]
fixed

https://github.com/wenet-e2e/WeTextProcessing/pull/131

**Comment by HankLiu10** [comment]
谢谢，完美解决
