### ISSUE TITLE
_pywrapfst. FstOpError: Operation failed

### ISSUE THREAD

**Issue by alibabadoufu** [wenet-e2e/WeTextProcessing#85]
<img width="1393" alt="image" src="https://github.com/wenet-e2e/WeTextProcessing/assets/47876361/67409ce2-af4d-47ba-b102-3bac6d6e7776">

Why there is such problem?

**Comment by xingchensong** [comment]
Could you provide your input text for us to repro this issue

**Comment by alibabadoufu** [comment]
> Could you provide your input text and running cmd for us to repro this issue

Hi I think I couldn't reproduce the error. I will close this issue for now until I encounter the same issue again. Thanks a lot for your reply.

**Comment by HankLiu10** [comment]
您好，我也遇到了此问题：
(wenetITN) liuhangchen@G08:~/WeNetITN/WeTextProcessing-master/itn/chinese$ weitn --text "二点五平方电线"
Traceback (most recent call last):
  File "/storage1/liuhangchen/anaconda3/envs/wenetITN/bin/weitn", line 8, in <module>
    sys.exit(main())
  File "/storage1/liuhangchen/anaconda3/envs/wenetITN/lib/python3.8/site-packages/itn/main.py", line 43, in main
    normalizer = InverseNormalizer(
  File "/storage1/liuhangchen/anaconda3/envs/wenetITN/lib/python3.8/site-packages/itn/chinese/inverse_normalizer.py", line 41, in __init__
    self.build_fst('zh_itn', cache_dir, overwrite_cache)
  File "/storage1/liuhangchen/anaconda3/envs/wenetITN/lib/python3.8/site-packages/tn/processor.py", line 74, in build_fst
    self.build_tagger()
  File "/storage1/liuhangchen/anaconda3/envs/wenetITN/lib/python3.8/site-packages/itn/chinese/inverse_normalizer.py", line 44, in build_tagger
    tagger = (add_weight(Date().tagger, 1.02)
  File "/storage1/liuhangchen/anaconda3/envs/wenetITN/lib/python3.8/site-packages/itn/chinese/rules/date.py", line 25, in __init__
    self.build_tagger()
  File "/storage1/liuhangchen/anaconda3/envs/wenetITN/lib/python3.8/site-packages/itn/chinese/rules/date.py", line 29, in build_tagger
    digit = string_file('itn/chinese/data/number/digit.tsv')  # 1 ~ 9
  File "extensions/_pynini.pyx", line 1033, in _pynini.string_file
  File "extensions/_pynini.pyx", line 1109, in _pynini.string_file
_pywrapfst.FstIOError: Read failed
