### ISSUE TITLE
[Install]直接从github code上安装会有问题

### ISSUE THREAD

**Issue by scutcsq** [wenet-e2e/WeTextProcessing#98]
当运行python setup.py install时，这两行代码会报错
# version = sys.argv[-1].split('=')[1]
# sys.argv = sys.argv[0:len(sys.argv) - 1]

error：
Traceback (most recent call last):
  File "setup.py", line 24, in <module>
    setup(
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-speech/users/chenshuaiqi03/install/envs/a100_py38/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-speech/users/chenshuaiqi03/install/envs/a100_py38/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 140, in setup
    attrs['script_name'] = os.path.basename(sys.argv[0])
IndexError: list index out of range
另还有错误为：
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

当把这两行注释掉，把26行的version内容命为1.2就能安装

**Comment by xingchensong** [comment]
参考下这一行本地build 
https://github.com/wenet-e2e/WeTextProcessing/blob/master/.github/workflows/wheels.yml#L50
